export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-primary-fixed": "#002022",
        "inverse-on-surface": "#313031",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#23005b",
        "inverse-surface": "#e5e2e3",
        "surface-container-highest": "#353436",
        "secondary-fixed-dim": "#ebb2ff",
        "on-surface": "#e5e2e3",
        "tertiary-fixed": "#e9ddff",
        "primary": "#e1fdff",
        "on-primary-fixed-variant": "#004f54",
        "secondary-fixed": "#f8d8ff",
        "primary-fixed-dim": "#00dbe7",
        "on-secondary": "#520071",
        "outline-variant": "#3a494b",
        "on-surface-variant": "#b9cacb",
        "tertiary": "#fcf5ff",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1c1b1c",
        "on-background": "#e5e2e3",
        "on-secondary-fixed": "#320047",
        "on-tertiary-container": "#7318ff",
        "surface-container": "#201f20",
        "surface": "#131314",
        "on-secondary-fixed-variant": "#74009f",
        "surface-bright": "#3a393a",
        "surface-variant": "#353436",
        "surface-tint": "#00dbe7",
        "on-primary-container": "#006a71",
        "outline": "#849495",
        "error": "#ffb4ab",
        "primary-fixed": "#74f5ff",
        "secondary": "#ebb2ff",
        "surface-container-high": "#2a2a2b",
        "on-tertiary": "#3c0090",
        "on-primary": "#00363a",
        "on-error": "#690005",
        "inverse-primary": "#00696f",
        "surface-dim": "#131314",
        "tertiary-container": "#e3d4ff",
        "surface-container-lowest": "#0e0e0f",
        "background": "#131314",
        "primary-container": "#00f2ff",
        "secondary-container": "#ce5dff",
        "on-tertiary-fixed-variant": "#5700c9",
        "tertiary-fixed-dim": "#d1bcff",
        "on-secondary-container": "#480064"
      },
      "spacing": {
        "xxl": "64px",
        "xs": "4px",
        "container-max": "1280px",
        "sm": "8px",
        "lg": "24px",
        "gutter": "24px",
        "xl": "40px",
        "unit": "4px",
        "md": "16px"
      },
      "fontFamily": {
        "label-caps": ["Inter"],
        "headline-md": ["Outfit"],
        "body-lg": ["Inter"],
        "display-lg": ["Outfit"],
        "mono-tech": ["Inter"],
        "headline-sm": ["Outfit"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "display-sm": ["Outfit"]
      },
      "fontSize": {
        "label-caps": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "mono-tech": ["13px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "headline-sm": ["20px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "1.4", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "display-sm": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
